import * as CKEditor5 from 'ckeditor5'

import { EditorConfig } from '../../interfaces/editor-config.interface'
import { BaseConfig } from './base'
// import { StrapiMediaLibPlugin } from '../../plugins/strapi-media-lib.plugin'

export const RichConfig: EditorConfig = {
  ...BaseConfig,
  plugins: [
    CKEditor5.Alignment,
    CKEditor5.Autoformat,
    CKEditor5.Bold,
    CKEditor5.Italic,
    CKEditor5.Underline,
    CKEditor5.Strikethrough,
    CKEditor5.Code,
    CKEditor5.CodeBlock,
    CKEditor5.GeneralHtmlSupport,
    CKEditor5.Subscript,
    CKEditor5.Superscript,
    CKEditor5.BlockQuote,
    CKEditor5.Essentials,
    CKEditor5.FontSize,
    CKEditor5.FontFamily,
    CKEditor5.FontColor,
    CKEditor5.FontBackgroundColor,
    CKEditor5.FindAndReplace,
    CKEditor5.Heading,
    CKEditor5.HorizontalLine,
    CKEditor5.HtmlEmbed,
    CKEditor5.Image,
    CKEditor5.ImageCaption,
    CKEditor5.ImageStyle,
    CKEditor5.ImageToolbar,
    CKEditor5.ImageUpload,
    CKEditor5.ImageResize,
    CKEditor5.Indent,
    CKEditor5.IndentBlock,
    CKEditor5.Link,
    CKEditor5.LinkImage,
    CKEditor5.List,
    CKEditor5.ListProperties,
    CKEditor5.TodoList,
    CKEditor5.MediaEmbed,
    CKEditor5.Paragraph,
    CKEditor5.PasteFromOffice,
    CKEditor5.RemoveFormat,
    CKEditor5.SpecialCharacters,
    CKEditor5.SpecialCharactersArrows,
    CKEditor5.SpecialCharactersEssentials,
    CKEditor5.SpecialCharactersCurrency,
    CKEditor5.SpecialCharactersLatin,
    CKEditor5.SpecialCharactersMathematical,
    CKEditor5.SpecialCharactersText,
    CKEditor5.Table,
    CKEditor5.TableToolbar,
    CKEditor5.TableProperties,
    CKEditor5.TableCellProperties,
    CKEditor5.TableColumnResize,
    CKEditor5.TableCaption,
    CKEditor5.WordCount,
    CKEditor5.Highlight,
    CKEditor5.SourceEditing,
    // StrapiMediaLibPlugin,
  ],
  toolbar: {
    items: [
      'undo',
      'redo',
      '|',
      'findAndReplace',
      'selectAll',
      '|',
      'heading',
      '|',
      'fontSize',
      'fontFamily',
      'fontColor',
      'fontBackgroundColor',
      '|',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'superscript',
      'subscript',
      'code',
      'removeFormat',
      '-',
      'link',
      // 'strapiMediaLib',
      'mediaEmbed',
      'insertTable',
      'horizontalLine',
      'blockQuote',
      'codeBlock',
      'htmlEmbed',
      'specialCharacters',
      'highlight',
      '|',
      'alignment',
      '|',
      'bulletedList',
      'numberedList',
      'todoList',
      'outdent',
      'indent',
      '|',
      'SourceEditing',
    ],
    shouldNotGroupWhenFull: true,
  },
  heading: {
    options: [
      { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
      { model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
      { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
      { model: 'heading3', view: 'h3', title: 'Heading 3', class: 'ck-heading_heading3' },
      { model: 'heading4', view: 'h4', title: 'Heading 4', class: 'ck-heading_heading4' },
    ],
  },
  list: {
    properties: {
      styles: true,
      startIndex: true,
      reversed: true,
    },
  },
  image: {
    resizeUnit: "%",
    resizeOptions: [
      {
        name: 'resizeImage:original',
        value: null,
        icon: 'original',
      },
      {
        name: 'resizeImage:25',
        value: '25',
        icon: 'small',
      },
      {
        name: 'resizeImage:50',
        value: '50',
        icon: 'medium',
      },
      {
        name: 'resizeImage:75',
        value: '75',
        icon: 'large',
      },
    ],
    toolbar: [
      'imageStyle:inline', 'imageStyle:block', 'imageStyle:side',
      '|',
      'toggleImageCaption', 'imageTextAlternative',
      '|',
      'linkImage',
      '|',
      'resizeImage:25', 'resizeImage:50', 'resizeImage:75', 'resizeImage:original',
    ],
  },
  table: {
    contentToolbar: [
      'tableColumn',
      'tableRow',
      'mergeTableCells',
      '|',
      'tableCellProperties',
      'tableProperties',
      '|',
      'toggleTableCaption',
    ],
  },
  fontSize: {
    options: [
      9,
      11,
      13,
      'default',
      17,
      19,
      21,
      27,
      35,
    ],
    supportAllValues: false,
  },
  fontFamily: {
    options: [
      'default',
      'Arial, Helvetica Neue, Helvetica, Source Sans Pro, sans-serif',
      'Courier New, Courier, monospace',
      'Georgia, serif',
      'Lucida Sans Unicode, Lucida Grande, sans-serif',
      'Tahoma, Geneva, sans-serif',
      'Times New Roman, Times, serif',
      'Trebuchet MS, Helvetica, sans-serif',
      'Verdana, Geneva, sans-serif',
      'Roboto, Roboto Black, Roboto Medium, Roboto Light, sans-serif',
    ],
    supportAllValues: true,
  },
  fontColor: {
    columns: 5,
    documentColors: 10,
  },
  fontBackgroundColor: {
    columns: 5,
    documentColors: 10,
  },
  link: {
    decorators: {
      openInNewTab: {
        mode: 'manual',
        label: 'Open in a new tab',
        attributes: {
          target: '_blank',
          rel: 'noopener noreferrer',
        },
      },
    },
  },
}

// export const RichConfig = BaseConfig
