import * as CKEditor5 from 'ckeditor5'

import { EditorConfig } from '../../../interfaces/editor-config.interface'

export const BasePlugins : EditorConfig['plugins'] = [
  CKEditor5.Alignment,
  CKEditor5.Autoformat,
  CKEditor5.AutoImage,
  CKEditor5.BlockQuote,
  CKEditor5.Bold,
  CKEditor5.Code,
  CKEditor5.CodeBlock,
  CKEditor5.Essentials,
  CKEditor5.FontBackgroundColor,
  CKEditor5.FontColor,
  CKEditor5.FontFamily,
  CKEditor5.FontSize,
  CKEditor5.GeneralHtmlSupport,
  CKEditor5.Heading,
  CKEditor5.HorizontalLine,
  CKEditor5.HtmlEmbed,
  CKEditor5.Image,
  CKEditor5.ImageCaption,
  CKEditor5.ImageInsert,
  CKEditor5.ImageResize,
  CKEditor5.ImageStyle,
  CKEditor5.ImageToolbar,
  CKEditor5.ImageUpload,
  CKEditor5.Indent,
  CKEditor5.IndentBlock,
  CKEditor5.Italic,
  CKEditor5.List,
  CKEditor5.ListProperties,
  CKEditor5.Link,
  CKEditor5.LinkImage,
  CKEditor5.MediaEmbed,
  CKEditor5.PageBreak,
  CKEditor5.Paragraph,
  CKEditor5.PasteFromOffice,
  CKEditor5.PictureEditing,
  CKEditor5.RemoveFormat,
  CKEditor5.SpecialCharacters,
  CKEditor5.SpecialCharactersArrows,
  CKEditor5.SpecialCharactersCurrency,
  CKEditor5.SpecialCharactersLatin,
  CKEditor5.SpecialCharactersMathematical,
  CKEditor5.SpecialCharactersText,
  CKEditor5.Strikethrough,
  CKEditor5.Style,
  CKEditor5.Subscript,
  CKEditor5.Superscript,
  CKEditor5.ShowBlocks,
  CKEditor5.Table,
  CKEditor5.TableCaption,
  CKEditor5.TableCellProperties,
  CKEditor5.TableColumnResize,
  CKEditor5.TableProperties,
  CKEditor5.TableToolbar,
  CKEditor5.Underline,
  CKEditor5.WordCount,
  CKEditor5.SourceEditing,
  // StrapiPlugins.StrapiMediaLib,
  // StrapiPlugins.StrapiUploadAdapter,
]
